import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider
  // SignedIn,
  // SignedOut,
  // SignInButton
  // UserButton
} from "@clerk/nextjs";

const playfairFont = Playfair({
  variable: "--playfairFont",
  subsets: ["latin-ext"],
  weight: ["300", "400", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${playfairFont.variable} antialiased`}>
          {/* <SignedOut>
            <SignInButton forceRedirectUrl={"/dashboard"} />
          </SignedOut> */}
          {/* <SignedIn>
            <UserButton />
          </SignedIn> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
